@extends('frontend.layout.layout')
@section('content')
<div id="Content-Container">
    <div id="Content-Main">
        <div class="table-div">
            <div id="Content" class="table-cell">
                <article class="textMain foterpagestextalign">
                    <h1>Privacy Policy<span>WE UNITE 91 (“WE UNITE 91” "we", “us”) are committed to protecting and respecting your privacy.</span></h1>
                    <p>This privacy policy applies to the website www.weunite91.com owned and operated by M/s WE UNITE 91 Limited (acting as data controller). This privacy policy describes how WE UNITE 91 collects and uses the personal data you provide on www.weunite91.com. It also describes the choices available to you regarding our use of your personal data and how you can access and update this information (see "Your rights" section for more details).</p>
                    <h3>Information we may collect from you</h3>
                    <p>We may collect and process the following data about you provided at the time of requesting goods, services or information from us:</p>
                    <p>Information that you provide to us by filling in forms on our site www.weunite91.com. This include contact information such as name, email address, mailing address, phone number, financial information such as bank or brokerage account numbers, unique identifiers such as user name, account number, password, date of birth and preferences information such as favourite’s lists, transaction history, marketing preferences. If you chose to list your company with us, we may ask for information about your business such as company name, company size, business type and personal data such as a professional profile.
                    </p>
                    <p>Information that you provide to us when you write to us (including by email).</p>
                    <p>Information that you provide to us when we speak to you by telephone. We may make and keep a record of the information you share with us.</p>
                    <p>Information that you provide to us by completing surveys.</p>
                    <p>Details of transactions you carry out through Our Site and of the fulfilment of your orders.</p>
                    <p>Information obtained by us from third parties in accordance with this Privacy Policy. For example, if you chose to list your business with us, we may Obtain additional information from credit reference agencies as a supplementary source.</p>
                    <p>As is true of most websites, we gather certain information automatically and store it in log files. This information includes internet protocol (IP) addresses, browser type, internet service provider (ISP), referring/exit pages, operating system, date/time stamp, and click stream data. We use this information, to analyze trends, to administer Our Site, to track users’ movements around Our Site and to gather demographic information about our user base as a whole.</p>
                    <h3>Uses made of the information</h3>
                    <p>We use information held about you in the following ways:</p>
                    <p>To ensure that content from Our Site is presented in the most effective manner for you and for your computer. This is in our legitimate business interests.</p>
                    <p>To provide you with information, products or services that may be of interest to you, where you have consented to be contacted for such purposes.</p>
                    <p>To carry out our obligations arising from (i) legal obligations and/or (ii) any contracts entered into between you and us to provide information, products or services that you have requested and notify you about changes to our goods and services.</p>
                    <p>If you are an existing customer/member, we may contact you by electronic means (Phone, Email or SMS) with information about goods and services similar to those which were the subject of a previous sale to you. We will not otherwise contact you by electronic means to provide you with information about goods and services which may be of interest to you, unless you have consented to this.</p>
                    <h3>Disclosure of your information</h3>
                    <p>We will share your personal data with third parties only in the ways that are described in this privacy policy. We do not sell your personal data to third parties. We may disclose your personal data to any member of our group, which means our subsidiaries, our ultimate holding company and its subsidiaries. In addition to the above, we may disclose your personal data to third parties:</p>
                    <p>In the event that we sell or buy any business or assets, in which case we may disclose your personal data to the prospect seller or buyer of such business or assets. You will be notified via email and/or prominent notice on Our Site of any change in ownership or uses of your personal data, as well as any choices you may have regarding your personal data.</p>
                    <p>If WE UNITE 91 or substantially all of its assets are acquired by a third party, in which case personal data held by it about its customers will be one of the transferred assets.</p>
                    <p>If we are, or believe in good faith that we are, under a duty to disclose or share your personal data in order to comply with any legal obligation; or permitted by law in order to enforce or apply our Terms and Conditions of Website Use and other agreements; or to protect the rights, property, or safety of us, our customers, or others. This includes exchanging information with other companies and organizations for the purposes of fraud protection and credit risk reduction.</p>
                    <p>If you have made an investment or applied to invest in a company via www.weunite91.com, your personal data may be disclosed to the company (or the company's professional representatives) that you have invested or applied to invest in. If you request a business plan, Follow a pitch or contact a business or entrepreneur via a pitch page your contact details may also be shared with that business or entrepreneur.</p>
                    <p>We may provide your personal data to companies that provide services to help us with our business activities such as shipping your order, processing payments, offering customer services or to improve our business operations. These companies are authorized to use your personal data only as necessary to provide these services to us.</p>
                    <p>We do not disclose information about identifiable individuals to our advertisers, but we may provide them with aggregate information about our users (for example, we may inform them that 200 men aged under 35 have clicked on their advertisement on any given day). We may also use such aggregate information to help advertisers reach the kind of audience they want to target. We may make use of the personal data we have collected from you to enable us to comply with our advertisers' wishes by displaying their advertisements to that target audience.</p>
                    <h4>Your rights</h4>
                    <p>You have the right to access information that is held about you. To protect your privacy and security, we’ll take reasonable steps to verify your identity before providing copies of any relevant materials. You may be entitled to ask us:</p>
                    <p>For a copy of your information.</p>
                    <p>To correct or erase your information.</p>
                    <p>To restrict or stop the processing information.</p>
                    <p>To transfer some of this information to other organisations.</p>
                    <p>Where we have asked for your consent to process your data, to withdraw this consent.</p>
                    <p>These rights may be limited in some situations – for example, where we can demonstrate that we have a legal requirement to process your data. In some instances, this may mean that we are able to retain data even if you withdraw your consent.</p>
                    <p>Where we require information to comply with legal or contractual obligations, then provision of such data is mandatory: if such information is not provided, then we will not be able to meet obligations placed on us or manage your transactions on Our Site. In all other cases, provision of requested information is optional. We hope that we can satisfy queries you may have about the way we process your information and resolve any complaints you may have. We encourage you to come to us in the first instance but you are entitled to complain directly to the relevant data protection authority.</p>
                    <h3>How to exercise your rights</h3>
                    <p>You can correct, change or delete your information in your member account setting page. You can stop receiving our newsletters or marketing emails by following the unsubscribe instructions included in these emails or accessing the email preferences in your account settings page. Alternatively, or to access any of the other above rights, you can email at info@weunite91.com or postal mail at the contact information listed below.</p>
                    <h3>How long we retain your information</h3>
                    <p>We will retain your information for as long as your account is active or as needed to provide you services. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements, which in some cases involving the collection and processing of financial data may require a retention period of 7 years (or longer if required by law).</p>
                    <h3>Cookies and tracking technologies</h3>
                    <p>Technologies such as: cookies, beacons, tags and scripts are used by WE UNITE 91 and our partners, including marketing partner’s affiliates, or analytics service providers and business process service providers. These technologies are used in analyzing trends, administering Our Site, tracking users’ movements around Our Site and to gather demographic information about our user base as a whole. We may receive reports based on the use of these technologies by these companies on an individual as well as aggregated basis.</p>
                    <p>We use cookies for to estimate our audience size and usage pattern; to store information about your preferences, and so allow us to customize Our Site according to your individual interests; to speed up your searches; and to recognize you when you return to Our Site. Users can control the use of cookies at the individual browser level. If you reject cookies, you may still use Our Site, but your ability to use some features or areas of Our Site may be limited.</p>
                    <p>We partner with third party ad networks to either display advertising on Our Site or to manage our advertising on other sites. Our ad network partner uses cookies and Web beacons to collect non-personal data about your activities on this and other Web sites to provide you targeted advertising based upon your interests. Additionally, we use an ad-publishing service to display 3rd party ads on Our Site. When you view or click on an ad, a cookie will be set to help better provide advertisements that may be of interest to you on this and other Web sites. You may opt-out of the use of this cookie by visiting the above tracking preference managers.</p>
                    <p>Local Storage Objects (Flash/HTML5): Third parties with whom we partner to provide certain features on Our Site or to display advertising based upon your Web browsing activity use LSOs such as HTML 5 or Flash to collect and store information. Various browsers may offer their own management tools for removing HTML5 LSOs.</p>
                    <h3>Security</h3>
                    <p>All information you provide to us via email or Our Site is stored on secure servers. Where we have given you (or where you have chosen) a password which enables you to access certain parts of Our Site, you are responsible for keeping this password confidential. We ask you not to share a password with anyone. The security of your personal data is important to us. When you enter sensitive information (such as bank account information) on our order forms, we encrypt the transmission of that information using secure socket layer technology (SSL). We follow generally accepted standards to protect the personal data submitted to us, both during transmission and once we receive it. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, we cannot guarantee its absolute security. If you have any questions about security on Our Site, you can contact us at info@weunite91.com</p>
                    <h3>Additional privacy information</h3>
                    <p><b>Blogs/Discussions</b> : Our Site offers a publicly accessible blog and community discussions. You should be aware that any information you provide in these areas may be read, collected, and used by others who access them. To request removal of your personal data from our blog or community discussions, contact us at info@weunite91.com. In some cases, we may not be able to remove your personal data, in which case we will let you know if we are unable to do so and why.</p>
                    <p><b>Referrals</b> : If you choose to use our referral service to tell a contact about Our Site, we will ask you for your contact’s name and email address. You must have consent from your contact to provide this information to us. We will automatically send your contact a one-time email inviting him or her to visit the site. WE UNITE91 store this information for the sole purpose of sending this one-time email and tracking the success of our referral program. Your contact may contact us at info@weunite91.com to request that we remove this information from our database.</p>
                    <p><b>Links to 3rd Party Sites</b> : Our Site may, from time to time, contain links to and from the websites of our suppliers, partner networks, advertisers, affiliates and other third parties. If you follow a link to any of these websites, please note that these websites should have their own privacy policies and we do not accept any responsibility or liability for these policies or the content or operation of these websites. Please check these policies and the terms of the websites before you submit any personal data to these websites.</p>
                    <p><b>Member Directory</b> : We will list you in our publicly accessible member directory. If you wish to request removal of your information or the deletion of an unauthorized profile from our directory, you can contact us at info@weunite91.com.</p>
                    <p><b>Profiles</b> : The profile you create on Our Site will be publicly accessible unless otherwise indicated. You may change the privacy settings of your profile through your account portal.</p>
                    <p><b>Social Media Widgets</b> : Our Site includes Social Media Features, such as the Facebook Like button, Twitter, LinkedIn, Instagram &amp; Google. These Features may collect your IP address, which page you are visiting on Our Site, and may set a cookie to enable the Feature to function properly. Social Media Features and Widgets are either hosted by a third party or hosted directly on Our Site. Your interactions with these Features are governed by the privacy policy of the company providing it.</p>
                    <p><b>Single Sign-On</b> : You can log in to Our Site using the sign-in service such as LinkedIn, Facebook, Twitter and Google. These services will authenticate your identity and provide you the option to share certain personal data with us such as your name and email address to pre-populate our sign up form. Services like LinkedIn, Facebook and Google may give you the option to post information about your activities on Our Site to your profile page to share with others within your network.</p>
                    <p><b>Changes to our privacy policy</b> : We may update this privacy policy to reflect changes to our information practices. If we make any material changes, we will notify you by email (sent to the e-mail address specified in your account) or by means of a notice on Our Site prior to the change becoming effective. We encourage you to periodically review this page for the latest information on our privacy practices.</p>
                    <p><b>Contact</b> : Questions, comments and requests regarding these privacy policies are welcomed and should be addressed to:</p>
                    <p><b>Office Timings</b><br>
                        Monday to Friday – 09:30 to 18:00 <br>
                        Saturday &amp; Sunday - CLOSED <br>
                        Email: info@weunite91.com </p>

                </article>
            </div>
        </div>
    </div>
</div>	
@endsection